### PR TITLE
User data bags source

### PR DESCRIPTION
**Pull request by mburns**
# What

Be able to load auth strings from `user` data_bags.
# Why

This will let us make onboarding a new users 1 step: user data bag. It eliminates updating the templates for the various web apps (Dreadnot, Buildbot).
# How

consolidates the logic from https://github.com/racker/chef/pull/3860

### CODE REVIEW

**Comment by drenalin23** [comment]
lgtm

**Comment by mburns** [comment]
tests were failing because the `cm0testenv3`'s token key was outdated. fixed.

**Comment by mburns** [comment]
```
       [2016-08-12T04:20:06+00:00] ERROR: Failed to load data bag item: "htpasswd" "test"
       
       ================================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/test/recipes/default.rb
       ================================================================================
       
       Net::HTTPServerException
       ------------------------
       404 "Not Found"
       
       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/test/recipes/default.rb:8:in `from_file'
       
       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/test/recipes/default.rb:
       
         1:  #
         2:  # Cookbook Name:: test
         3:  # Recipe:: default
         4:  #
         5:  # License:: Apache License, Version 2.0
         6:  #
         7:  
         8>> credentials = data_bag_item('htpasswd', 'test')['users']
```

**Comment by drenalin23** [comment]
It would be great to figure out how to mock out data_bags in kitchen tests!

**Pull request closed without merging**
